import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main className="w-full grid grid-row-[auto_1fr_auto] gap-[32px] lg:gap-[64px]">
          <Navbar title="Couchsurfing" />
          <div className="w-full lg:mx-auto lg:max-w-[1128px]">{children}</div>
          <Footer text="© 2025 Couchsurfing" />
        </main>
      </body>
    </html>
  );
}
